name:                servant-myproj
version:             0.1.0.0
github:              "ssipos90/servant-myproj"
license:             BSD3
author:              "Sebastian Sipos"
maintainer:          "sebastiansipos90@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssipos90/servant-myproj#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- mtl
- postgresql-simple
- resource-pool
- servant
- servant-server
- wai
- warp

default-extensions:
- LambdaCase
- OverloadedStrings


library:
  source-dirs: src

executables:
  servant-myproj-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-myproj

tests:
  servant-myproj-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-myproj
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
